### PR TITLE
Static file caching

### PR DESCRIPTION
**Pull request by pascalopitz**
This controls caching behavior via using the startup time as `last-modified` and subsequent validation of `if-modified-since`

### CODE REVIEW

**Comment by pascalopitz** [comment]
I assume that before the actual file meta data could be used as `last-modified`, whereas for embedded assets that's not happening? We can think of the startup time as the last time something gets modified though,

**Comment by buro9** [comment]
This is elegant and a far simpler fix than the one I was thinking of :)

**Comment by pascalopitz** [comment]
Well, my first thought was "ETAG" but I think this works just as well

**Comment by buro9** [comment]
Fixes #128

**Comment by buro9** [comment]
Well my thought was:
1. Generate SHA hashes of all files.
2. Populate a map of file names to hashes.
3. Allow templates to obtain the hash (new filename) from the map.
4. Force super long "forever cache" HTTP heads.

Works because we never need to invalidate any cache even when files change as the changed files are new files and templates would always point at new files.

Also would allow the hashes to be accessed for subresource integrity.

**Pull request merged**
